version: '2'
services:
  blog-app:
    image: blog
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://blog-mysql:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_CACHE_REDIS_SERVER=redis://blog-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://blog-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://blog-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://blog-elasticsearch:9200
    ports:
      - 8080:8080
  blog-mysql:
    extends:
      file: mysql.yml
      service: blog-mysql
  blog-redis:
    extends:
      file: redis.yml
      service: blog-redis
  blog-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: blog-elasticsearch
